# Generated by Django 4.1 on 2022-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0013_alter_academicinfo_registration_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicinfo",
            name="registration_no",
            field=models.IntegerField(default=186954, unique=True),
        ),
    ]
